-- MYSQL
SELECT * FROM `CITY` WHERE `COUNTRYCODE` = "USA" AND `POPULATION` > 100000;

-- ORACLE
SELECT * FROM "CITY" WHERE "COUNTRYCODE" = 'USA' AND "POPULATION" > 100000;

-- MS SQL
SELECT * FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;

--DB2
SELECT * FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 100000;