-- MYSQL
SELECT `NAME` FROM `CITY` WHERE `COUNTRYCODE` = "USA" AND `POPULATION` > 120000;

-- ORACLE
SELECT "NAME" FROM "CITY" WHERE "COUNTRYCODE" = 'USA' AND "POPULATION" > 120000;

-- MS SQL
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;

--DB2
SELECT NAME FROM CITY WHERE COUNTRYCODE = 'USA' AND POPULATION > 120000;